export const ENV_NAMES = {
  PORT: "PORT",
  FRONTEND_URL: "FRONTEND_URL",
  DATABASE_URL: "DATABASE_URL",
  GOOGLE_CLIENT_ID: "GOOGLE_CLIENT_ID",
  GOOGLE_CLIENT_SECRET: "GOOGLE_CLIENT_SECRET",
  GITHUB_CLIENT_ID: "GITHUB_CLIENT_ID",
  GITHUB_CLIENT_SECRET: "GITHUB_CLIENT_SECRET",
  GOOGLE_CALLBACK_URL: "GOOGLE_CALLBACK_URL",
  GITHUB_CALLBACK_URL: "GITHUB_CALLBACK_URL",
  JWT_SECRET: "JWT_SECRET",
  SALTS_ROUNDS: "SALTS_ROUNDS",
};
