export const ENV_NAMES = {
  PORT: "PORT",
  FRONTEND_URL: "FRONTEND_URL",
  DATABASE_URL: "DATABASE_URL",
  GOOGLE_CLIENT_ID: "GOOGLE_CLIENT_ID",
  GOOGLE_CLIENT_SECRET: "GOOGLE_CLIENT_SECRET",
  FACEBOOK_CLIENT_ID: "FACEBOOK_CLIENT_ID",
  FACEBOOK_CLIENT_SECRET: "FACEBOOK_CLIENT_SECRET",
  JWT_SECRET: "JWT_SECRET",
};
